/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type SiteInfo = {
    site: ({
        siteMetadata: ({
            source: string | null;
            address: string | null;
        }) | null;
    }) | null;
};
export type SiteInfoVariables = {};
